--[[       This is a wind genorator. Its uses the power givin
in the 'Configuration' to push parts in the given direction.
It does not effect anchored parts or parts that have a string
value inside of them named 'NO WIND'.
For direction the following keywords are not case sensitive and will
work:
- Up
- Down
- West
- East
- North
- South

They can be used in any order such as NORTHWESTUP is equal to
UpNoRtHwEsT. Any double negitives will cancel and do nothing like
North;South;West will only go west. You can also seperate them
how ever you feel. Like North:West,Up.        ]]--

$      :Made by BrainWart:     $